version: '2'
services:

  db:
    image: mariadb
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: YOURPASSWORD
    volumes:
      - /PATH/TO/PERSISTENT/FILES/db:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    depends_on:
      - "db"
    environment:
      - VIRTUAL_HOST=mysql.YOURDOMAIN.com
      - LETSENCRYPT_HOST=mysql.YOURDOMAIN.com
      - LETSENCRYPT_EMAIL=YOUREMAIL
      - PMA_HOST=db
    ports:
      - "1666:80" 

  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always
    environment:
      - VIRTUAL_HOST=docker.YOURDOMAIN.com
      - LETSENCRYPT_HOST=docker.YOURDOMAIN.com
      - LETSENCRYPT_EMAIL=EMAIL
    volumes: 
      - /PATH/TO/PERSISTENT/FILES:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9000:9000"

  nextcloud:
    image: nextcloud:apache
    container_name: nextcloud
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=cloud.YOURDOMAIN.com
      - LETSENCRYPT_HOST=cloud.YOURDOMAIN.com
      - LETSENCRYPT_EMAIL=YOUREMAIL
      - PGID=999
      - PUID=1000
    ports:
      - "666:80"
    volumes:
      - /PATH/TO/PERSISTENT/FILES/nextcloud:/var/www/html
      - /PATH/TO/PERSISTENT/FILES/nextcloud/uploadsize.conf:/etc/nginx/conf.d/uploadsize.conf
    depends_on:
      - "db"
    links:
      - "redis"
    networks:
      - proxy-tier
      - default
 
  proxy:
    build: ./proxy   
    container_name: proxy
    restart: unless-stopped
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    environment:
      - DEFAULT_HOST=cloud.YOURDOMAIN.com
    ports:
      - "80:80"
      - "443:443"
    networks:
      - "default"
      - "proxy-tier"

  proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    restart: unless-stopped
    environment:
      - NGINX_PROXY_CONTAINER=proxy
    depends_on:
      - "proxy"
    volumes_from:
      - "proxy"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - "default"
      - "proxy-tier"

volumes:
  certs:
  vhost.d:
  html:

networks:
  proxy-tier:
